
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC-oUX6sD1Mqqtq9KY5Ch1xXAZaddGX9-E",
      authDomain: "prohealth-symmetry.firebaseapp.com",
      projectId: "prohealth-symmetry",
      storageBucket: "prohealth-symmetry.firebasestorage.app",
      messagingSenderId: "1037706652640",
      appId: "1:1037706652640:web:127c168dd6aeab92b15985",
      measurementId: "G-LHX0KPW6NP"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyC-oUX6sD1Mqqtq9KY5Ch1xXAZaddGX9-E",
      authDomain: "prohealth-symmetry.firebaseapp.com",
      projectId: "prohealth-symmetry",
      storageBucket: "prohealth-symmetry.firebasestorage.app",
      messagingSenderId: "1037706652640",
      appId: "1:1037706652640:web:127c168dd6aeab92b15985",
      measurementId: "G-LHX0KPW6NP"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyC-oUX6sD1Mqqtq9KY5Ch1xXAZaddGX9-E",
      authDomain: "prohealth-symmetry.firebaseapp.com",
      projectId: "prohealth-symmetry",
      storageBucket: "prohealth-symmetry.firebasestorage.app",
      messagingSenderId: "1037706652640",
      appId: "1:1037706652640:web:127c168dd6aeab92b15985",
      measurementId: "G-LHX0KPW6NP"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyC-oUX6sD1Mqqtq9KY5Ch1xXAZaddGX9-E",
      authDomain: "prohealth-symmetry.firebaseapp.com",
      projectId: "prohealth-symmetry",
      storageBucket: "prohealth-symmetry.firebasestorage.app",
      messagingSenderId: "1037706652640",
      appId: "1:1037706652640:web:127c168dd6aeab92b15985",
      measurementId: "G-LHX0KPW6NP"
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyCIberUASN5W6CgMIE1f00kwNMJY5HwVQg",
      authDomain: "communication-40093.firebaseapp.com",
      projectId: "communication-40093",
      storageBucket: "communication-40093.firebasestorage.app",
      messagingSenderId: "114032294912",
      appId: "1:114032294912:web:cd373273ae45e626d92ce5",
      measurementId: "G-LMNRWF5TVJ"
  );
}
